"""First migration

Revision ID: 1208cfe29d19
Revises: None
Create Date: 2015-10-13 15:17:47.681000

"""

# revision identifiers, used by Alembic.
revision = '1208cfe29d19'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='users'
    )
    op.create_table('userinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('fullname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=250), nullable=True),
    sa.Column('picture_url', sa.String(length=250), nullable=True),
    sa.Column('quota', sa.Integer(), nullable=True),
    sa.Column('disk_used', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='users'
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('datestamp', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.userinfo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='portal'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles', schema='portal')
    op.drop_table('userinfo', schema='users')
    op.drop_table('roles', schema='users')
    ### end Alembic commands ###
