"""Adding signature support

Revision ID: 175613d5f86
Revises: 3f53a2a2d88
Create Date: 2015-12-21 10:02:40.496000

"""

# revision identifiers, used by Alembic.
revision = '175613d5f86'
down_revision = '3f53a2a2d88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signature_html', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('signature_text', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signature_text')
    op.drop_column('users', 'signature_html')
    ### end Alembic commands ###
