"""Adding user roles

Revision ID: 1cc83180017c
Revises: 48d2caae4bbc
Create Date: 2015-10-25 11:21:51.475000

"""

# revision identifiers, used by Alembic.
revision = '1cc83180017c'
down_revision = '48d2caae4bbc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'users', 'roles', ['roles_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'roles_id')
    ### end Alembic commands ###
