"""Visibility tag added to articles

Revision ID: 1d9dde62aab6
Revises: 551667531ccf
Create Date: 2015-10-16 07:34:19.199000

"""

# revision identifiers, used by Alembic.
revision = '1d9dde62aab6'
down_revision = '551667531ccf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('visibility', sa.Boolean(), default=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'visibility')
    ### end Alembic commands ###
