"""Add cascade deletion of posts when parent thread is removed

Revision ID: 237fb3593010
Revises: 5aaecbb33a86
Create Date: 2015-12-04 08:28:41.410000

"""

# revision identifiers, used by Alembic.
revision = '237fb3593010'
down_revision = '5aaecbb33a86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'post_thread_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'thread', ['thread'], ['id'], ondelete='cascade')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(u'post_thread_fkey', 'post', 'thread', ['thread'], ['id'])
    ### end Alembic commands ###
