"""Adding posts relation to thread

Revision ID: 26d78bb59769
Revises: 392637bb25e8
Create Date: 2015-12-01 22:32:27.051000

"""

# revision identifiers, used by Alembic.
revision = '26d78bb59769'
down_revision = '392637bb25e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('html_body', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('thread', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'thread', ['thread'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'thread')
    op.drop_column('post', 'html_body')
    ### end Alembic commands ###
