"""Cleaning up some namespace collisions

Revision ID: 2b8b1a3f0f49
Revises: 237fb3593010
Create Date: 2015-12-05 10:10:59.316000

"""

# revision identifiers, used by Alembic.
revision = '2b8b1a3f0f49'
down_revision = '237fb3593010'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('author', sa.Integer(), nullable=True))
    op.drop_constraint(u'thread_thread_author_fkey', 'thread', type_='foreignkey')
    op.create_foreign_key(None, 'thread', 'users', ['author'], ['id'])
    op.drop_column('thread', 'thread_author')
    op.drop_column('users', 'posts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('posts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('thread', sa.Column('thread_author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.create_foreign_key(u'thread_thread_author_fkey', 'thread', 'users', ['thread_author'], ['id'])
    op.drop_column('thread', 'author')
    ### end Alembic commands ###
