"""Adding 2FA flag

Revision ID: 38c35c71e23d
Revises: 1d9dde62aab6
Create Date: 2015-10-16 20:03:38.301000

"""

# revision identifiers, used by Alembic.
revision = '38c35c71e23d'
down_revision = '1d9dde62aab6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp_secret', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('tfa', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tfa')
    op.drop_column('users', 'otp_secret')
    ### end Alembic commands ###
