"""Adding restriction to threads

Revision ID: 392637bb25e8
Revises: 415f68fe6444
Create Date: 2015-12-01 07:40:16.901000

"""

# revision identifiers, used by Alembic.
revision = '392637bb25e8'
down_revision = '415f68fe6444'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum', sa.Column('restricted', sa.Boolean(), default=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum', 'restricted')
    ### end Alembic commands ###
