"""empty message

Revision ID: 3ad3c0708773
Revises: 22a5a81ab591
Create Date: 2015-11-11 17:37:45.276000

"""

# revision identifiers, used by Alembic.
revision = '3ad3c0708773'
down_revision = '22a5a81ab591'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('html_body', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'html_body')
    ### end Alembic commands ###
