"""Adding forum roles

Revision ID: 3c0a98c2c0fa
Revises: 111859e5812c
Create Date: 2015-11-27 16:09:21.311000

"""

# revision identifiers, used by Alembic.
revision = '3c0a98c2c0fa'
down_revision = '111859e5812c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_forum_roles_default'), 'forum_roles', ['default'], unique=False)
    op.add_column(u'users', sa.Column('forum_roles_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'forum_roles', ['forum_roles_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column(u'users', 'forum_roles_id')
    op.drop_index(op.f('ix_forum_roles_default'), table_name='forum_roles')
    op.drop_table('forum_roles')
    ### end Alembic commands ###
