"""Adding post count to user model

Revision ID: 3f53a2a2d88
Revises: 2b8b1a3f0f49
Create Date: 2015-12-05 11:12:34.968000

"""

# revision identifiers, used by Alembic.
revision = '3f53a2a2d88'
down_revision = '2b8b1a3f0f49'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('post_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'post_count')
    ### end Alembic commands ###
