"""Adding posts table

Revision ID: 415f68fe6444
Revises: 1e98a7f9d497
Create Date: 2015-12-01 07:21:20.882000

"""

# revision identifiers, used by Alembic.
revision = '415f68fe6444'
down_revision = '1e98a7f9d497'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poster', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('edit_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['poster'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'thread', sa.Column('last_post', sa.DateTime(), nullable=False))
    op.drop_constraint(u'thread_fk_forum_fkey', 'thread', type_='foreignkey')
    op.create_foreign_key(None, 'thread', 'forum', ['fk_forum'], ['id'], ondelete='cascade')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thread', type_='foreignkey')
    op.create_foreign_key(u'thread_fk_forum_fkey', 'thread', 'forum', ['fk_forum'], ['id'])
    op.drop_column(u'thread', 'last_post')
    op.drop_table('post')
    ### end Alembic commands ###
