"""Moving OTP out of user data

Revision ID: 48d2caae4bbc
Revises: 38c35c71e23d
Create Date: 2015-10-17 22:42:45.477000

"""

# revision identifiers, used by Alembic.
revision = '48d2caae4bbc'
down_revision = '38c35c71e23d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'otp_fk_userid_key', 'otp', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'otp_fk_userid_key', 'otp', ['fk_userid'])
    ### end Alembic commands ###
