"""Moving OTP secret out of user table

Revision ID: 4d92e08b1204
Revises: 38c35c71e23d
Create Date: 2015-10-17 08:58:35.551000

"""

# revision identifiers, used by Alembic.
revision = '4d92e08b1204'
down_revision = '38c35c71e23d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import Sequence, CreateSequence

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_userid', sa.Integer(), nullable=False),
    sa.Column('secret', sa.String(length=16), nullable=False),
    sa.Column('backup_code', postgresql.ARRAY(sa.String(length=16)), nullable=True),
    sa.ForeignKeyConstraint(['fk_userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('secret')
    )
    op.execute(CreateSequence(Sequence("otp_id_seq")))
    op.drop_column(u'users', 'otp_secret')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'users', sa.Column('otp_secret', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.drop_table('otp')
    ### end Alembic commands ###
