"""Adding forum table

Revision ID: 50d93e0d716f
Revises: 3c0a98c2c0fa
Create Date: 2015-11-30 22:07:28.193000

"""

# revision identifiers, used by Alembic.
revision = '50d93e0d716f'
down_revision = '3c0a98c2c0fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forums')
    ### end Alembic commands ###
