"""Adding user avatar text

Revision ID: 551667531ccf
Revises: 29ca84572eec
Create Date: 2015-10-15 21:57:16.728000

"""

# revision identifiers, used by Alembic.
revision = '551667531ccf'
down_revision = '29ca84572eec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_text', sa.String(length=250), nullable=True))
    op.add_column('users', sa.Column('threads_posted_to', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'threads_posted_to')
    op.drop_column('users', 'avatar_text')
    ### end Alembic commands ###
