"""Adding view count to threads

Revision ID: 5aaecbb33a86
Revises: 26d78bb59769
Create Date: 2015-12-02 08:21:12.534000

"""

# revision identifiers, used by Alembic.
revision = '5aaecbb33a86'
down_revision = '26d78bb59769'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thread', sa.Column('views', sa.Integer(), server_default='0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thread', 'views')
    ### end Alembic commands ###
