"""empty message

Revision ID: 7ec2b4fc374
Revises: 1208cfe29d19
Create Date: 2015-10-13 16:42:35.827000

"""

# revision identifiers, used by Alembic.
revision = '7ec2b4fc374'
down_revision = '1208cfe29d19'

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column('userinfo', sa.Column('timezone', sa.String(20), default='US/Pacific'), schema='users')
    op.alter_column('userinfo', 'password_hash', type_=sa.CHAR(160), schema='users')

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userinfo', 'timezone', schema='users')