from sqlalchemy import Integer, INTEGER

"""Pluralizing backup_codes in OTP table.

Revision ID: d172e1e1059e
Revises: 175613d5f86
Create Date: 2016-08-27 16:52:43.735000

"""

# revision identifiers, used by Alembic.
revision = 'd172e1e1059e'
down_revision = '175613d5f86'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('backup_codes', postgresql.ARRAY(Integer()), nullable=True))
    op.drop_column('otp', 'backup_code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('backup_code', postgresql.ARRAY(INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('otp', 'backup_codes')
    ### end Alembic commands ###
